encoding    : UTF-8
exclude     : [.idea]

title       : YouTube Geofind
subtitle    : Discover Geo-tagged Videos
author      : mattwright324
copyright   : 2021
home        : https://conork360.io/
github      : https://github.com/conork360/
github_repo : https://github.com/conork360/mynewsite/
gh_pages    : https://conork360.github.io/mynewsite/
url: https://conork360.github.io
baseurl: /mynewsite